CREATE DATABASE bobo;
-- 會員資料;
CREATE TABLE MEMBER(
  ID VARCHAR(20) PRIMARY KEY,
  Password VARCHAR(128) NOT NULL,
  Name VARCHAR(12) NOT NULL,
  Money VARCHAR(20) NOT NULL,
  Email VARCHAR(30) NOT NULL,
  Phone VARCHAR(10) NOT NULL,
  RegDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  Birth DATE,
  Gender ENUM('M', 'F', 'N'),
  Address VARCHAR(100),
  Position ENUM('S', 'A', 'C') 
);

-- 提款;
CREATE TABLE PRODUCT(
  pid INT(7) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  ID VARCHAR(20),
  Number INT(3)  DEFAULT NULL,
  Number2 INT(7) DEFAULT NULL,
  Name VARCHAR(7) DEFAULT NULL,
  Price INT(10) UNSIGNED DEFAULT NULL,
  total INT(10) UNSIGNED DEFAULT NULL,
  Img VARCHAR(100) DEFAULT NULL,
  Info VARCHAR(300),
  ptime VARCHAR(100) DEFAULT NULL,
  CategoryID INT(7) UNSIGNED DEFAULT NULL
  REFERENCES MEMBER(ID)
);



-- 類型;
CREATE TABLE CATEGORY(
  ID INT(7) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  Name VARCHAR(10) NOT NULL UNIQUE
);

-- VIEW 視界;

DROP VIEW IF EXISTS PRODUCT_VIEW;


CREATE VIEW PRODUCT_VIEW
AS SELECT P.pid PP ,P.ID PID ,P.Number Number ,P.Number2 Number2 ,P.Name PName ,P.Info PInfo ,P.Img PImg ,
          C.Name CName ,C.ID CID ,P.Price PPriceF ,P.total Ptotal ,P.ptime Ptime
           FROM PRODUCT P
           INNER JOIN CATEGORY C ON P.CategoryID = C.ID
           WHERE P.CategoryID = C.ID
           ORDER BY PID;

        